<?php

use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;

const DOG_BREEDS_LIST_VIEW_ID = 'dog_breeds_list_test_1';
const FIELD_SLUG_MACHINE_NAME = 'field_slug';
const DOG_API_URL = 'https://dog.ceo/api/breed/';
const DOG_API_RANDOM_IMAGE_PATH = '/images/random';

/**
 * Implements hook_views_pre_render().
 */
function dog_breeds_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if ($view->id() != DOG_BREEDS_LIST_VIEW_ID) {
    return;
  }

  // Loop to interact with the dog breeds list view.
  foreach ($view->result as $value) {
    $fieldSlugValue = $value->_entity->get(FIELD_SLUG_MACHINE_NAME)->value;
    $urlImage = getUrlImageFromDogApi($fieldSlugValue);

    // Set image field URL value.
    // $value->_entity->set('field_image', $urlImage);
  }
}

/**
 * Prepare the url to access the dog api service to get a dog breed's random image.
 */
function prepareUrlToDogApi($fieldSlugValue) : string {
  $url_formatted = DOG_API_URL . $fieldSlugValue . DOG_API_RANDOM_IMAGE_PATH;

  return $url_formatted;
}

/**
 * Get the url image.
 */
function getUrlImageFromDogApi($fieldSlugValue) : string {
  $urlFormatted = prepareUrlToDogApi($fieldSlugValue);

  $urlImage = getRequestToDogApi($urlFormatted);

  return $urlImage;
}

/**
 * Do the get request to the dog api service.
 */
function getRequestToDogApi($url) {
  $client = new Client();
  
  try {
    $response = $client->get($url);
    $result = json_decode($response->getBody(), TRUE);

    if($result['status'] != 'success') {
      return;
    }

    return $result['message'];
  }
  catch (RequestException $exception) {
    // log exception
    echo '<pre>'; var_dump($exception); echo '</pre>';
  }
}